remote_theme: pmarsceill/just-the-docs
baseurl: "/laraval-doc-cn" # the subpath of your site, e.g. /blog
url: "https://ericyue2012.github.io" # the base hostname & protocol for your site, e.g. http://example.com